// Generated by Wrangler by running `wrangler types`

interface Env {
	users: KVNamespace;
	problemTree: R2Bucket;
	JWT_SECRET: string;
	OPENAI_API_KEY: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
